    // ===== รูปภาพเครื่องมือ (INSTRUMENT IMAGES) =====
    // =====================================================================
    // วิธีใส่รูปเครื่องมือใหม่ (แพทเทิร์นเดียวกับที่ใช้ในหน้า personnel.html และ activities.html):
    //   1) เตรียมไฟล์รูปภาพ (.jpg .jpeg .png .webp)
    //   2) นำไฟล์รูปไปวางไว้ในโฟลเดอร์ "images/" (ระดับเดียวกับไฟล์ index.html นี้)
    //      แนะนำให้สร้างโฟลเดอร์ย่อย เช่น "images/equipment/" เพื่อความเป็นระเบียบ ก็ทำได้เช่นกัน
    //   3) เพิ่ม/แก้ไขบรรทัดด้านล่างนี้ โดยฝั่งซ้าย (key) ต้อง "พิมพ์ตรงกับชื่อเครื่องมือ (instrument)
    //      ในตัวแปร serviceData ทุกตัวอักษร" ฝั่งขวา (value) คือ path ไปยังไฟล์รูปที่วางไว้
    //
    //   ตัวอย่าง: เครื่องมือชื่อ "Flow cytometer" มีไฟล์รูปชื่อ flow-cytometer.jpg
    //   ก็ให้เพิ่มบรรทัด:   "Flow cytometer": "images/flow-cytometer.jpg",
    //
    //   หมายเหตุ: ถ้าเครื่องมือไหนยังไม่มีรูป (ไม่ได้ใส่ไว้ใน map นี้) ระบบจะแสดงกรอบว่างแทน
    //   โดยอัตโนมัติ ไม่ต้องกังวลว่าเว็บจะพัง
    // =====================================================================
    const instrumentImages = {
      "Biomolecular imager": "images/Imager.png",
      "Image analyzer": "images/image-analyzer.png",
      "Microplate reader": "images/microplate-reader.png",
      "Automated western blot": "images/jess.png",
      "Biomolecular imager": "images/typhoon.png",
      "ELISpot": "images/elispot.png",
      "Flow cytometer": "images/flow.png",
      "Fragment analyzer": "images/fragment.png",
      "Gel documentation": "images/gel doc.png",
      "MALDI-TOF MS": "images/maldi.png",
      "PCR machine": "images/pcr.png",
      "Sequencer": "images/sequencer.png",
      "Surface plasmon resonance": "images/biacore.png",
      "DART-MS": "images/dart.png",
      "FPLC": "images/fplc.png",
      "GC": "images/gc.png",
      "GC-MS": "images/gc-ms.png",
      "GC-TQ": "images/gc-tq.png",
      "HPLC": "images/hplc.png",
      "LC-MS-QTOF": "images/lc-ms-qtof.png",
      "LC-MS-": ""

      // เพิ่มรูปอื่นๆ ตามชื่อเครื่องมือได้เลย
    };

    // ฟังก์ชันสลับไปแสดงกรอบว่าง เมื่อโหลดรูปไม่สำเร็จ (เรียกจาก onerror ของ <img>)
    // ⚠️ ใช้ฟังก์ชันแบบนี้เสมอ ห้ามฝัง HTML/SVG ที่มีเครื่องหมาย " ลงในแอตทริบิวต์ onerror="..." ตรงๆ
    // เพราะจะไปชนกับเครื่องหมาย " ที่ล้อมรอบ onerror เอง ทำให้ HTML พังตั้งแต่ตอนแปลงหน้าเว็บ
    function showInstrumentFallback(imgEl) {
      imgEl.outerHTML = '<div class="instrument-img-placeholder"></div>';
    }
    const serviceData = [
      // ────────────────── Bioscience instrument ──────────────────
      { group: "Bioscience instrument", instrument: "Automated western blot", code: "BS01-1A", mode: "Automated western blot - chemiluminescence (Instrument use)", unit: "run", mahidol: 500, gov: 650, priv: 1000 },
      { group: "Bioscience instrument", instrument: "Automated western blot", code: "BS01-2A", mode: "Automated western blot - fluorescence (Instrument use)", unit: "run", mahidol: 650, gov: 850, priv: 1300 },
      { group: "Bioscience instrument", instrument: "Biomolecular imager", code: "BS02-1A", mode: "Biomolecular imager (Instrument use)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Bioscience instrument", instrument: "Biomolecular imager", code: "BS02-1B", mode: "Biomolecular imager (Program analysis)", unit: "hour", mahidol: 50, gov: 75, priv: 100 },
      { group: "Bioscience instrument", instrument: "ELISpot", code: "BS04-1A", mode: "ELISpot (Instrument use)", unit: "hour", mahidol: 300, gov: 400, priv: 600 },
      { group: "Bioscience instrument", instrument: "ELISpot", code: "BS04-1B", mode: "ELISpot (Program analysis)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Bioscience instrument", instrument: "Flow cytometer", code: "BS05-1A", mode: "Flow cytometer - analyzer (Instrument use)", unit: "hour", mahidol: 1000, gov: 1250, priv: 2000 },
      { group: "Bioscience instrument", instrument: "Flow cytometer", code: "BS05-2A", mode: "Flow cytometer - cell sorter (Instrument use)", unit: "hour", mahidol: 1200, gov: 1500, priv: 2400 },
      { group: "Bioscience instrument", instrument: "Flow cytometer", code: "BS05-1B", mode: "Flow cytometer - analyzer (Program analysis)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Bioscience instrument", instrument: "Fragment analyzer", code: "BS06-1A", mode: "Fragment analyzer (Instrument use)", unit: "hour", mahidol: 450, gov: 600, priv: 900 },
      { group: "Bioscience instrument", instrument: "Gel documentation", code: "BS07-1A", mode: "Gel documentation (Instrument use)", unit: "hour", mahidol: 50, gov: 75, priv: 100 },
      { group: "Bioscience instrument", instrument: "Image analyzer", code: "BS08-1A", mode: "Image analyzer (Instrument use)", unit: "hour", mahidol: 250, gov: 350, priv: 500 },
      { group: "Bioscience instrument", instrument: "Incubator", code: "BS09-1A", mode: "CO2 incubator (Instrument use)", unit: "hour", mahidol: 30, gov: 40, priv: 60 },
      { group: "Bioscience instrument", instrument: "Incubator", code: "BS09-2A", mode: "Cooling incubator (Instrument use)", unit: "hour", mahidol: 30, gov: 40, priv: 60 },
      { group: "Bioscience instrument", instrument: "Incubator", code: "BS09-3A", mode: "Heating incubator (Instrument use)", unit: "hour", mahidol: 30, gov: 40, priv: 60 },
      { group: "Bioscience instrument", instrument: "Incubator", code: "BS09-4A", mode: "Shaking incubator (Instrument use)", unit: "hour", mahidol: 30, gov: 40, priv: 60 },
      { group: "Bioscience instrument", instrument: "Microplate reader", code: "BS10-1A", mode: "Microplate reader - absorbance (Instrument use)", unit: "hour", mahidol: 100, gov: 150, priv: 200 },
      { group: "Bioscience instrument", instrument: "Microplate reader", code: "BS10-2A", mode: "Microplate reader - alpha screen (Instrument use)", unit: "hour", mahidol: 150, gov: 200, priv: 300 },
      { group: "Bioscience instrument", instrument: "Microplate reader", code: "BS10-3A", mode: "Microplate reader - chemiluminescence (Instrument use)", unit: "hour", mahidol: 150, gov: 200, priv: 300 },
      { group: "Bioscience instrument", instrument: "Microplate reader", code: "BS10-4A", mode: "Microplate reader - fluorescence (Instrument use)", unit: "hour", mahidol: 150, gov: 200, priv: 300 },
      { group: "Bioscience instrument", instrument: "Microplate reader", code: "BS10-5A", mode: "Microplate reader - fluorescence polarization (Instrument use)", unit: "hour", mahidol: 150, gov: 200, priv: 300 },
      { group: "Bioscience instrument", instrument: "Microplate reader", code: "BS10-6A", mode: "Microplate reader - time resolved fluorescence (Instrument use)", unit: "hour", mahidol: 150, gov: 200, priv: 300 },
      { group: "Bioscience instrument", instrument: "Microplate reader", code: "BS10-7A", mode: "Microplate reader - time resolved FRET (Instrument use)", unit: "hour", mahidol: 150, gov: 200, priv: 300 },
      { group: "Bioscience instrument", instrument: "MALDI-TOF MS", code: "BS11-1A", mode: "MALDI-TOF MS (Instrument use)", unit: "hour", mahidol: 1250, gov: 1600, priv: 2500 },
      { group: "Bioscience instrument", instrument: "MALDI-TOF MS", code: "BS11-2A", mode: "MALDI-TOF MS - genotyping analysis (Instrument use)", unit: "hour", mahidol: 900, gov: 1150, priv: 1800 },
      { group: "Bioscience instrument", instrument: "MALDI-TOF MS", code: "BS11-3A", mode: "MALDI-TOF MS - MALDI-imaging (Instrument use)", unit: "hour", mahidol: 2200, gov: 2750, priv: 4400 },
      { group: "Bioscience instrument", instrument: "MALDI-TOF MS", code: "BS11-1B", mode: "MALDI-TOF MS (Program analysis)", unit: "hour", mahidol: 550, gov: 700, priv: 1100 },
      { group: "Bioscience instrument", instrument: "MALDI-TOF MS", code: "BS11-2B", mode: "MALDI-TOF MS - genotyping analysis (Program analysis)", unit: "hour", mahidol: 450, gov: 600, priv: 900 },
      { group: "Bioscience instrument", instrument: "MALDI-TOF MS", code: "BS11-1D", mode: "MALDI-TOF MS - biotyper (Test)", unit: "sample", mahidol: 500, gov: 650, priv: 1000 },
      { group: "Bioscience instrument", instrument: "MALDI-TOF MS", code: "BS11-2D", mode: "MALDI-TOF MS - protein molecular weight measurement (Test)", unit: "sample", mahidol: 1000, gov: 1250, priv: 2000 },
      { group: "Bioscience instrument", instrument: "MALDI-TOF MS", code: "BS11-3D", mode: "MALDI-TOF MS - polymer (Test)", unit: "sample", mahidol: 1300, gov: 1650, priv: 2600 },
      { group: "Bioscience instrument", instrument: "PCR machine", code: "BS12-1A", mode: "PCR machine (Instrument use)", unit: "hour", mahidol: 100, gov: 150, priv: 200 },
      { group: "Bioscience instrument", instrument: "PCR machine", code: "BS12-2A", mode: "Real-time PCR machine (Instrument use)", unit: "hour", mahidol: 300, gov: 400, priv: 600 },
      { group: "Bioscience instrument", instrument: "Sequencer", code: "BS13-1A", mode: "Benchtop sequencer (Instrument use)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Bioscience instrument", instrument: "Sequencer", code: "BS13-2A", mode: "Production-scale sequencer (Instrument use)", unit: "hour", mahidol: 300, gov: 400, priv: 600 },
      { group: "Bioscience instrument", instrument: "Sequencer", code: "BS13-1C", mode: "Benchtop sequencer (Test and analysis)", unit: "hour", mahidol: 300, gov: 400, priv: 600 },
      { group: "Bioscience instrument", instrument: "Sequencer", code: "BS13-2C", mode: "Production-scale sequencer (Test and analysis)", unit: "hour", mahidol: 450, gov: 600, priv: 900 },
      { group: "Bioscience instrument", instrument: "Sequencer", code: "BS13-3C", mode: "Bioinformatics service (Test and analysis)", unit: "hour", mahidol: 1000, gov: 1250, priv: 2000 },
      { group: "Bioscience instrument", instrument: "Sequencer", code: "BS13-1D", mode: "Benchtop sequencer - DNA library preparation (Test, 8-24 Samples)", unit: "sample", mahidol: 1600, gov: 2000, priv: 3200 },
      { group: "Bioscience instrument", instrument: "Sequencer", code: "BS13-2D", mode: "Benchtop sequencer - PCR amplicon preparation (Test, 8-96 Samples)", unit: "sample", mahidol: 550, gov: 700, priv: 1100 },
      { group: "Bioscience instrument", instrument: "Sequencer", code: "BS13-3D", mode: "Production-scale sequencer - RNA library preparation (Test, 8-16 Samples)", unit: "sample", mahidol: 1600, gov: 2000, priv: 3200 },
      { group: "Bioscience instrument", instrument: "Sequencer", code: "BS13-4D", mode: "Production-scale sequencer - whole genome library preparation (Test, 8-24 Samples)", unit: "sample", mahidol: 1600, gov: 2000, priv: 3200 },
      { group: "Bioscience instrument", instrument: "Surface plasmon resonance", code: "BS14-1A", mode: "Surface plasmon resonance (Instrument use)", unit: "hour", mahidol: 350, gov: 450, priv: 700 },

      // ────────────────── Chromatograph ──────────────────
      { group: "Chromatograph", instrument: "DART-MS", code: "CG01-1A", mode: "DART-MS (Instrument use)", unit: "hour", mahidol: 700, gov: 900, priv: 1400 },
      { group: "Chromatograph", instrument: "DART-MS", code: "CG01-1D", mode: "DART-MS (Test)", unit: "sample", mahidol: 800, gov: 1000, priv: 1600 },
      { group: "Chromatograph", instrument: "FPLC", code: "CG02-1A", mode: "FPLC (Instrument use)", unit: "hour", mahidol: 120, gov: 150, priv: 250 },
      { group: "Chromatograph", instrument: "FPLC", code: "CG02-2A", mode: "FPLC - preparative (Instrument use)", unit: "hour", mahidol: 300, gov: 400, priv: 600 },
      { group: "Chromatograph", instrument: "Flash chromatograph", code: "CG03-1A", mode: "Flash chromatograph (Instrument use)", unit: "hour", mahidol: 500, gov: 650, priv: 1000 },
      { group: "Chromatograph", instrument: "Flash chromatograph", code: "CG03-2A", mode: "Flash chromatograph (Instrument use with user column)", unit: "hour", mahidol: 450, gov: 600, priv: 900 },
      { group: "Chromatograph", instrument: "GC", code: "CG04-1A", mode: "GC (Instrument use)", unit: "hour", mahidol: 250, gov: 350, priv: 500 },
      { group: "Chromatograph", instrument: "GC", code: "CG04-2A", mode: "GC (Instrument use with user column)", unit: "hour", mahidol: 225, gov: 300, priv: 450 },
      { group: "Chromatograph", instrument: "GC", code: "CG04-1B", mode: "GC (Program analysis)", unit: "hour", mahidol: 100, gov: 150, priv: 200 },
      { group: "Chromatograph", instrument: "GC", code: "CG04-1C", mode: "GC (Test and analysis)", unit: "sample", mahidol: 450, gov: 600, priv: 900 },
      { group: "Chromatograph", instrument: "GC", code: "CG04-2C", mode: "GC (Test and analysis with user column)", unit: "sample", mahidol: 400, gov: 550, priv: 800 },
      { group: "Chromatograph", instrument: "GC-MS", code: "CG05-1A", mode: "GC-MS (Instrument use)", unit: "hour", mahidol: 350, gov: 500, priv: 700 },
      { group: "Chromatograph", instrument: "GC-MS", code: "CG05-2A", mode: "GC-MS (Instrument use with user column)", unit: "hour", mahidol: 300, gov: 400, priv: 600 },
      { group: "Chromatograph", instrument: "GC-MS", code: "CG05-1B", mode: "GC-MS (Program analysis)", unit: "hour", mahidol: 150, gov: 200, priv: 300 },
      { group: "Chromatograph", instrument: "GC-MS", code: "CG05-1C", mode: "GC-MS - quantitative (Test and analysis)", unit: "sample", mahidol: 750, gov: 950, priv: 1500 },
      { group: "Chromatograph", instrument: "GC-MS", code: "CG05-2C", mode: "GC-MS - quantitative (Test and analysis with user column)", unit: "sample", mahidol: 700, gov: 850, priv: 1350 },
      { group: "Chromatograph", instrument: "GC-MS", code: "CG05-3C", mode: "GC-MS - quantitative head space/SPME (Test and analysis)", unit: "sample", mahidol: 1200, gov: 1500, priv: 2400 },
      { group: "Chromatograph", instrument: "GC-MS", code: "CG05-4C", mode: "GC-MS - quantitative head space/SPME (Test and analysis with user column)", unit: "sample", mahidol: 1100, gov: 1350, priv: 2200 },
      { group: "Chromatograph", instrument: "GC-MS", code: "CG05-1D", mode: "GC-MS - head space/SPME profile (Test)", unit: "sample", mahidol: 800, gov: 1000, priv: 1600 },
      { group: "Chromatograph", instrument: "GC-MS", code: "CG05-2D", mode: "GC-MS - head space/SPME profile (Test with user column)", unit: "sample", mahidol: 700, gov: 900, priv: 1400 },
      { group: "Chromatograph", instrument: "GC-MS", code: "CG05-3D", mode: "GC-MS - profile (Test)", unit: "sample", mahidol: 500, gov: 650, priv: 1000 },
      { group: "Chromatograph", instrument: "GC-MS", code: "CG05-4D", mode: "GC-MS - profile (Test with user column)", unit: "sample", mahidol: 450, gov: 600, priv: 900 },
      { group: "Chromatograph", instrument: "GC-TQ", code: "CG06-1A", mode: "GC-TQ (Instrument use)", unit: "hour", mahidol: 550, gov: 700, priv: 1100 },
      { group: "Chromatograph", instrument: "GC-TQ", code: "CG06-2A", mode: "GC-TQ (Instrument use with user column)", unit: "hour", mahidol: 500, gov: 650, priv: 1000 },
      { group: "Chromatograph", instrument: "GC-TQ", code: "CG06-1B", mode: "GC-TQ (Program analysis)", unit: "hour", mahidol: 300, gov: 400, priv: 600 },
      { group: "Chromatograph", instrument: "GC-TQ", code: "CG06-1C", mode: "GC-TQ - quantitative (Test and analysis)", unit: "sample", mahidol: 1250, gov: 1600, priv: 2500 },
      { group: "Chromatograph", instrument: "GC-TQ", code: "CG06-2C", mode: "GC-TQ - quantitative (Test and analysis with user column)", unit: "sample", mahidol: 1100, gov: 1400, priv: 2200 },
      { group: "Chromatograph", instrument: "GC-TQ", code: "CG06-3C", mode: "GC-TQ - quantitative head space/SPME (Test and analysis)", unit: "sample", mahidol: 1650, gov: 2100, priv: 3300 },
      { group: "Chromatograph", instrument: "GC-TQ", code: "CG06-4C", mode: "GC-TQ - quantitative head space/SPME (Test and analysis with user column)", unit: "sample", mahidol: 1500, gov: 1900, priv: 3000 },
      { group: "Chromatograph", instrument: "HPLC", code: "CG07-1A", mode: "HPLC - 2 channels UV detector (Instrument use)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Chromatograph", instrument: "HPLC", code: "CG07-2A", mode: "HPLC - 2 channels UV detector (Instrument use with user column)", unit: "hour", mahidol: 180, gov: 225, priv: 350 },
      { group: "Chromatograph", instrument: "HPLC", code: "CG07-3A", mode: "HPLC - 4 channels UV detector (Instrument use)", unit: "hour", mahidol: 250, gov: 350, priv: 500 },
      { group: "Chromatograph", instrument: "HPLC", code: "CG07-4A", mode: "HPLC - 4 channels UV detector (Instrument use with user column)", unit: "hour", mahidol: 225, gov: 320, priv: 450 },
      { group: "Chromatograph", instrument: "HPLC", code: "CG07-5A", mode: "HPLC - ELS detector (Instrument use)", unit: "hour", mahidol: 300, gov: 400, priv: 600 },
      { group: "Chromatograph", instrument: "HPLC", code: "CG07-6A", mode: "HPLC - ELS detector (Instrument use with user column)", unit: "hour", mahidol: 270, gov: 350, priv: 550 },
      { group: "Chromatograph", instrument: "HPLC", code: "CG07-7A", mode: "HPLC - fluorescence detector (Instrument use)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Chromatograph", instrument: "HPLC", code: "CG07-8A", mode: "HPLC - fluorescence detector (Instrument use with user column)", unit: "hour", mahidol: 180, gov: 225, priv: 350 },
      { group: "Chromatograph", instrument: "HPLC", code: "CG07-9A", mode: "HPLC - RI detector (Instrument use)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Chromatograph", instrument: "HPLC", code: "CG07-10A", mode: "HPLC - RI detector (Instrument use with user column)", unit: "hour", mahidol: 180, gov: 225, priv: 350 },
      { group: "Chromatograph", instrument: "LC-MS-QTOF", code: "CG08-1D", mode: "LC-MS-QTOF - HRMS (Test)", unit: "sample", mahidol: 400, gov: 500, priv: 800 },
      { group: "Chromatograph", instrument: "LC-MS-QTOF", code: "CG08-2D", mode: "LC-MS-QTOF - metabolite profiling (Test)", unit: "sample", mahidol: 3200, gov: 4000, priv: 6400 },
      { group: "Chromatograph", instrument: "LC-MS-QTOF", code: "CG08-3D", mode: "LC-MS-QTOF - method development (Test)", unit: "hour", mahidol: 1200, gov: 1500, priv: 2400 },
      { group: "Chromatograph", instrument: "LC-MS-TQ", code: "CG09-1A", mode: "LC-MS-TQ (Instrument use)", unit: "hour", mahidol: 550, gov: 700, priv: 1100 },
      { group: "Chromatograph", instrument: "LC-MS-TQ", code: "CG09-2A", mode: "LC-MS-TQ (Instrument use with user column)", unit: "hour", mahidol: 500, gov: 650, priv: 1000 },
      { group: "Chromatograph", instrument: "LC-MS-TQ", code: "CG09-1B", mode: "LC-MS-TQ (Program analysis)", unit: "hour", mahidol: 300, gov: 400, priv: 600 },
      { group: "Chromatograph", instrument: "LC-MS-TQ", code: "CG09-1C", mode: "LC-MS-TQ - quantitative (Test and analysis)", unit: "sample", mahidol: 1350, gov: 1750, priv: 2700 },
      { group: "Chromatograph", instrument: "LC-MS-TQ", code: "CG09-2C", mode: "LC-MS-TQ - quantitative (Test and analysis with user column)", unit: "sample", mahidol: 1200, gov: 1550, priv: 2400 },
      { group: "Chromatograph", instrument: "LC-MS-TQ", code: "CG09-1D", mode: "LC-MS-TQ - profile (Test)", unit: "sample", mahidol: 850, gov: 1050, priv: 1700 },
      { group: "Chromatograph", instrument: "LC-MS-TQ", code: "CG09-2D", mode: "LC-MS-TQ - profile (Test with user column)", unit: "sample", mahidol: 700, gov: 900, priv: 1400 },
      { group: "Chromatograph", instrument: "Preparative HPLC", code: "CG10-1A", mode: "Preparative HPLC (Instrument use)", unit: "hour", mahidol: 450, gov: 600, priv: 900 },
      { group: "Chromatograph", instrument: "Preparative HPLC", code: "CG10-2A", mode: "Preparative HPLC (Instrument use with user column)", unit: "hour", mahidol: 400, gov: 500, priv: 800 },
      { group: "Chromatograph", instrument: "UHPLC", code: "CG11-1A", mode: "UHPLC (Instrument use)", unit: "hour", mahidol: 300, gov: 400, priv: 600 },
      { group: "Chromatograph", instrument: "UHPLC", code: "CG11-2A", mode: "UHPLC (Instrument use with user column)", unit: "hour", mahidol: 250, gov: 350, priv: 500 },

      // ────────────────── Freezer ──────────────────
      { group: "Freezer", instrument: "Freezer", code: "FZ01-1A", mode: "-20°C freezer (Instrument use)", unit: "day", mahidol: 5, gov: 8, priv: 10 },
      { group: "Freezer", instrument: "Freezer", code: "FZ01-2A", mode: "-30°C freezer (Instrument use)", unit: "day", mahidol: 8, gov: 10, priv: 15 },
      { group: "Freezer", instrument: "Freezer", code: "FZ01-3A", mode: "-80°C freezer (Instrument use)", unit: "day", mahidol: 10, gov: 15, priv: 20 },
      { group: "Freezer", instrument: "Freezer", code: "FZ01-4A", mode: "4°C refrigerator (Instrument use)", unit: "day", mahidol: 5, gov: 8, priv: 10 },
      { group: "Freezer", instrument: "Freezer", code: "FZ01-5A", mode: "Liquid nitrogen tank (Instrument use)", unit: "day", mahidol: 15, gov: 20, priv: 30 },
      { group: "Freezer", instrument: "Freezer", code: "FZ01-6A", mode: "Ultra-low freezer -150°C (Instrument use)", unit: "day", mahidol: 15, gov: 20, priv: 30 },

      // ────────────────── Microscope ──────────────────
      { group: "Microscope", instrument: "Atomic force microscope : AFM", code: "MC01-1A", mode: "AFM (Instrument use)", unit: "hour", mahidol: 600, gov: 750, priv: 1200 },
      { group: "Microscope", instrument: "Atomic force microscope : AFM", code: "MC01-1B", mode: "AFM (Program analysis)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Microscope", instrument: "Atomic force microscope : AFM", code: "MC01-1D", mode: "AFM (Test)", unit: "hour", mahidol: 1200, gov: 1500, priv: 2400 },
      { group: "Microscope", instrument: "Confocal microscope", code: "MC02-1A", mode: "Confocal microscope (Instrument use)", unit: "hour", mahidol: 500, gov: 650, priv: 1000 },
      { group: "Microscope", instrument: "Confocal microscope", code: "MC02-1B", mode: "Confocal microscope (Program analysis)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Microscope", instrument: "Digital microscope", code: "MC03-1A", mode: "Digital microscope (Instrument use)", unit: "hour", mahidol: 150, gov: 200, priv: 300 },
      { group: "Microscope", instrument: "Fluorescence microscope", code: "MC04-1A", mode: "Fluorescence microscope (Instrument use)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Microscope", instrument: "Fluorescence microscope", code: "MC04-1B", mode: "Fluorescence microscope (Program analysis)", unit: "hour", mahidol: 100, gov: 150, priv: 200 },
      { group: "Microscope", instrument: "Inverted microscope", code: "MC05-1A", mode: "Inverted microscope (Instrument use)", unit: "hour", mahidol: 100, gov: 150, priv: 200 },
      { group: "Microscope", instrument: "Scanning electron microscope : SEM", code: "MC06-1A", mode: "SEM (Instrument use)", unit: "hour", mahidol: 500, gov: 650, priv: 1000 },
      { group: "Microscope", instrument: "Scanning electron microscope : SEM", code: "MC06-2A", mode: "SEM - EDS (Instrument use)", unit: "hour", mahidol: 700, gov: 900, priv: 1400 },
      { group: "Microscope", instrument: "Scanning electron microscope : SEM", code: "MC06-3A", mode: "SEM - EBSD (Instrument use)", unit: "hour", mahidol: 900, gov: 1150, priv: 1800 },
      { group: "Microscope", instrument: "Scanning electron microscope : SEM", code: "MC06-1B", mode: "SEM (Program analysis)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Microscope", instrument: "Scanning electron microscope : SEM", code: "MC06-2B", mode: "SEM - EDS (Program analysis)", unit: "hour", mahidol: 300, gov: 400, priv: 600 },
      { group: "Microscope", instrument: "Scanning electron microscope : SEM", code: "MC06-3B", mode: "SEM - EBSD (Program analysis)", unit: "hour", mahidol: 400, gov: 500, priv: 800 },
      { group: "Microscope", instrument: "Scanning electron microscope : SEM", code: "MC06-1D", mode: "SEM (Test)", unit: "hour", mahidol: 1000, gov: 1250, priv: 2000 },
      { group: "Microscope", instrument: "Scanning electron microscope : SEM", code: "MC06-2D", mode: "SEM - EDS (Test)", unit: "hour", mahidol: 1400, gov: 1750, priv: 2800 },
      { group: "Microscope", instrument: "Scanning electron microscope : SEM", code: "MC06-3D", mode: "SEM - EBSD (Test)", unit: "hour", mahidol: 1800, gov: 2250, priv: 3600 },
      { group: "Microscope", instrument: "Stereo microscope", code: "MC07-1A", mode: "Stereo microscope (Instrument use)", unit: "hour", mahidol: 100, gov: 150, priv: 200 },
      { group: "Microscope", instrument: "Transmission electron microscope : TEM", code: "MC08-1A", mode: "TEM (Instrument use)", unit: "hour", mahidol: 700, gov: 900, priv: 1400 },
      { group: "Microscope", instrument: "Transmission electron microscope : TEM", code: "MC08-1B", mode: "TEM (Program analysis)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Microscope", instrument: "Transmission electron microscope : TEM", code: "MC08-1D", mode: "TEM (Test)", unit: "hour", mahidol: 1400, gov: 1750, priv: 2800 },
      { group: "Microscope", instrument: "Upright microscope", code: "MC09-1A", mode: "Upright microscope (Instrument use)", unit: "hour", mahidol: 100, gov: 150, priv: 200 },
      { group: "Microscope", instrument: "Upright microscope", code: "MC09-2A", mode: "Upright microscope - polarization (Instrument use)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Microscope", instrument: "Upright microscope", code: "MC09-1B", mode: "Upright microscope (Program analysis)", unit: "hour", mahidol: 50, gov: 75, priv: 100 },
      { group: "Microscope", instrument: "Upright microscope", code: "MC09-1D", mode: "Upright microscope - material science (Test)", unit: "hour", mahidol: 250, gov: 350, priv: 500 },
      { group: "Microscope", instrument: "Upright microscope", code: "MC09-2D", mode: "Upright microscope - biological science (Test)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },

      // ────────────────── Sample preparation ──────────────────
      { group: "Sample preparation", instrument: "Autoclave", code: "SP01-1A", mode: "Autoclave (Instrument use)", unit: "hour", mahidol: 30, gov: 40, priv: 60 },
      { group: "Sample preparation", instrument: "Ball mill", code: "SP02-1A", mode: "Ball mill (Instrument use)", unit: "hour", mahidol: 100, gov: 150, priv: 200 },
      { group: "Sample preparation", instrument: "Biosafety cabinet", code: "SP03-1A", mode: "Biosafety cabinet (Instrument use)", unit: "hour", mahidol: 50, gov: 75, priv: 100 },
      { group: "Sample preparation", instrument: "Carbon coater", code: "SP04-1A", mode: "Carbon coater (Instrument use)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Sample preparation", instrument: "Centrifuge", code: "SP05-1A", mode: "Centrifuge (Instrument use)", unit: "hour", mahidol: 50, gov: 75, priv: 100 },
      { group: "Sample preparation", instrument: "Centrifuge", code: "SP05-2A", mode: "Ultracentrifuge (Instrument use)", unit: "hour", mahidol: 250, gov: 350, priv: 500 },
      { group: "Sample preparation", instrument: "Critical point dryer", code: "SP06-1A", mode: "Critical point dryer (Instrument use)", unit: "hour", mahidol: 250, gov: 350, priv: 500 },
      { group: "Sample preparation", instrument: "Cutting machine", code: "SP07-1A", mode: "Cutting machine (Instrument use)", unit: "hour", mahidol: 100, gov: 150, priv: 200 },
      { group: "Sample preparation", instrument: "Embedding machine", code: "SP08-1A", mode: "Embedding machine (Instrument use)", unit: "hour", mahidol: 100, gov: 150, priv: 200 },
      { group: "Sample preparation", instrument: "Freeze dryer", code: "SP09-1A", mode: "Freeze dryer (Instrument use)", unit: "hour", mahidol: 50, gov: 75, priv: 100 },
      { group: "Sample preparation", instrument: "Fume hood", code: "SP10-1A", mode: "Fume hood (Instrument use)", unit: "hour", mahidol: 30, gov: 40, priv: 60 },
      { group: "Sample preparation", instrument: "Grinder", code: "SP11-1A", mode: "Grinder (Instrument use)", unit: "hour", mahidol: 100, gov: 150, priv: 200 },
      { group: "Sample preparation", instrument: "Homogenizer", code: "SP12-1A", mode: "Homogenizer (Instrument use)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Sample preparation", instrument: "Hot plate/Stirrer", code: "SP13-1A", mode: "Hot plate/Stirrer (Instrument use)", unit: "hour", mahidol: 30, gov: 40, priv: 60 },
      { group: "Sample preparation", instrument: "Ion milling", code: "SP14-1A", mode: "Ion milling - cross section polisher (Instrument use)", unit: "hour", mahidol: 350, gov: 450, priv: 700 },
      { group: "Sample preparation", instrument: "Ion milling", code: "SP14-2A", mode: "Ion milling - flat milling (Instrument use)", unit: "hour", mahidol: 350, gov: 450, priv: 700 },
      { group: "Sample preparation", instrument: "Microbalance", code: "SP15-1A", mode: "Microbalance (Instrument use)", unit: "hour", mahidol: 30, gov: 40, priv: 60 },
      { group: "Sample preparation", instrument: "Microtome", code: "SP16-1A", mode: "Rotary microtome (Instrument use)", unit: "hour", mahidol: 100, gov: 150, priv: 200 },
      { group: "Sample preparation", instrument: "Microtome", code: "SP16-2A", mode: "Sliding microtome (Instrument use)", unit: "hour", mahidol: 100, gov: 150, priv: 200 },
      { group: "Sample preparation", instrument: "Microtome", code: "SP16-3A", mode: "Ultramicrotome (Instrument use)", unit: "hour", mahidol: 300, gov: 400, priv: 600 },
      { group: "Sample preparation", instrument: "Microwave digestion", code: "SP17-1A", mode: "Microwave digestion (Instrument use)", unit: "hour", mahidol: 250, gov: 350, priv: 500 },
      { group: "Sample preparation", instrument: "Mounting press", code: "SP18-1A", mode: "Mounting press (Instrument use)", unit: "hour", mahidol: 100, gov: 150, priv: 200 },
      { group: "Sample preparation", instrument: "Oven", code: "SP19-1A", mode: "Oven (Instrument use)", unit: "hour", mahidol: 30, gov: 40, priv: 60 },
      { group: "Sample preparation", instrument: "Polishing machine", code: "SP20-1A", mode: "Polishing machine (Instrument use)", unit: "hour", mahidol: 100, gov: 150, priv: 200 },
      { group: "Sample preparation", instrument: "Rotary evaporator", code: "SP21-1A", mode: "Rotary evaporator (Instrument use)", unit: "hour", mahidol: 100, gov: 150, priv: 200 },
      { group: "Sample preparation", instrument: "Sonication bath", code: "SP22-1A", mode: "Sonication bath (Instrument use)", unit: "hour", mahidol: 50, gov: 75, priv: 100 },
      { group: "Sample preparation", instrument: "Sputter coater", code: "SP23-1A", mode: "Sputter coater - Au (Instrument use)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Sample preparation", instrument: "Sputter coater", code: "SP23-2A", mode: "Sputter coater - Pt (Instrument use)", unit: "hour", mahidol: 350, gov: 450, priv: 700 },
      { group: "Sample preparation", instrument: "Spray dryer", code: "SP24-1A", mode: "Spray dryer (Instrument use)", unit: "hour", mahidol: 300, gov: 400, priv: 600 },
      { group: "Sample preparation", instrument: "Stainer", code: "SP25-1A", mode: "Stainer (Instrument use)", unit: "hour", mahidol: 100, gov: 150, priv: 200 },
      { group: "Sample preparation", instrument: "Tissue processor", code: "SP26-1A", mode: "Tissue processor (Instrument use)", unit: "hour", mahidol: 50, gov: 75, priv: 100 },
      { group: "Sample preparation", instrument: "Vacuum oven", code: "SP27-1A", mode: "Vacuum oven (Instrument use)", unit: "hour", mahidol: 50, gov: 75, priv: 100 },
      { group: "Sample preparation", instrument: "Vortex mixer", code: "SP28-1A", mode: "Vortex mixer (Instrument use)", unit: "hour", mahidol: 10, gov: 15, priv: 20 },
      { group: "Sample preparation", instrument: "Water bath", code: "SP29-1A", mode: "Water bath (Instrument use)", unit: "hour", mahidol: 20, gov: 30, priv: 40 },

      // ────────────────── Spectrometer ──────────────────
      { group: "Spectrometer", instrument: "Circular dichroism spectropolarimeter : CD", code: "SM01-1A", mode: "CD (Instrument use)", unit: "hour", mahidol: 450, gov: 600, priv: 900 },
      { group: "Spectrometer", instrument: "Circular dichroism spectropolarimeter : CD", code: "SM01-1B", mode: "CD (Program analysis)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Spectrometer", instrument: "Circular dichroism spectropolarimeter : CD", code: "SM01-1D", mode: "CD (Test)", unit: "sample", mahidol: 550, gov: 700, priv: 1100 },
      { group: "Spectrometer", instrument: "Dynamic light scattering", code: "SM02-1A", mode: "Dynamic light scattering (Instrument use)", unit: "hour", mahidol: 150, gov: 200, priv: 300 },
      { group: "Spectrometer", instrument: "Dynamic light scattering", code: "SM02-1D", mode: "Dynamic light scattering - particle size (Test)", unit: "sample", mahidol: 200, gov: 250, priv: 400 },
      { group: "Spectrometer", instrument: "Dynamic light scattering", code: "SM02-2D", mode: "Dynamic light scattering - zeta potential (Test)", unit: "sample", mahidol: 200, gov: 250, priv: 400 },
      { group: "Spectrometer", instrument: "Fluorescence spectrometer", code: "SM03-1A", mode: "Fluorescence spectrometer (Instrument use)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Spectrometer", instrument: "Fluorescence spectrometer", code: "SM03-1B", mode: "Fluorescence spectrometer (Program analysis)", unit: "hour", mahidol: 100, gov: 150, priv: 200 },
      { group: "Spectrometer", instrument: "Fluorescence spectrometer", code: "SM03-1D", mode: "Fluorescence spectrometer (Test)", unit: "sample", mahidol: 250, gov: 350, priv: 500 },
      { group: "Spectrometer", instrument: "FT-IR spectrometer", code: "SM04-1A", mode: "FT-IR (Instrument use)", unit: "hour", mahidol: 150, gov: 200, priv: 300 },
      { group: "Spectrometer", instrument: "FT-IR spectrometer", code: "SM04-2A", mode: "FT-IR microscope (Instrument use)", unit: "hour", mahidol: 500, gov: 650, priv: 1000 },
      { group: "Spectrometer", instrument: "FT-IR spectrometer", code: "SM04-1B", mode: "FT-IR (Program analysis)", unit: "hour", mahidol: 50, gov: 75, priv: 100 },
      { group: "Spectrometer", instrument: "FT-IR spectrometer", code: "SM04-2B", mode: "FT-IR microscope (Program analysis)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Spectrometer", instrument: "FT-IR spectrometer", code: "SM04-1D", mode: "FT-IR (Test)", unit: "sample", mahidol: 200, gov: 250, priv: 400 },
      { group: "Spectrometer", instrument: "FT-IR spectrometer", code: "SM04-2D", mode: "FT-IR microscope - point measurement (Test)", unit: "sample", mahidol: 700, gov: 900, priv: 1400 },
      { group: "Spectrometer", instrument: "FT-IR spectrometer", code: "SM04-3D", mode: "FT-IR microscope - mapping (Test)", unit: "hour", mahidol: 1200, gov: 1500, priv: 2400 },
      { group: "Spectrometer", instrument: "ICP-MS", code: "SM05-1A", mode: "ICP-MS (Instrument use)", unit: "hour", mahidol: 700, gov: 900, priv: 1400 },
      { group: "Spectrometer", instrument: "ICP-MS", code: "SM05-1B", mode: "ICP-MS (Program analysis)", unit: "hour", mahidol: 300, gov: 400, priv: 600 },
      { group: "Spectrometer", instrument: "ICP-MS", code: "SM05-1C", mode: "ICP-MS (Test and analysis)", unit: "sample", mahidol: 800, gov: 1000, priv: 1600 },
      { group: "Spectrometer", instrument: "ICP-OES", code: "SM06-1A", mode: "ICP-OES (Instrument use)", unit: "hour", mahidol: 550, gov: 700, priv: 1100 },
      { group: "Spectrometer", instrument: "ICP-OES", code: "SM06-1B", mode: "ICP-OES (Program analysis)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Spectrometer", instrument: "ICP-OES", code: "SM06-1C", mode: "ICP-OES (Test and analysis)", unit: "sample", mahidol: 600, gov: 750, priv: 1200 },
      { group: "Spectrometer", instrument: "Isothermal titration calorimeter : ITC", code: "SM07-1A", mode: "ITC (Instrument use)", unit: "hour", mahidol: 450, gov: 600, priv: 900 },
      { group: "Spectrometer", instrument: "Isothermal titration calorimeter : ITC", code: "SM07-1B", mode: "ITC (Program analysis)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Spectrometer", instrument: "Isothermal titration calorimeter : ITC", code: "SM07-1D", mode: "ITC (Test)", unit: "sample", mahidol: 1200, gov: 1500, priv: 2400 },
      { group: "Spectrometer", instrument: "Laser diffraction particle size analyzer", code: "SM08-1A", mode: "Laser diffraction particle size analyzer - wet measurement (Instrument use)", unit: "hour", mahidol: 250, gov: 350, priv: 500 },
      { group: "Spectrometer", instrument: "Laser diffraction particle size analyzer", code: "SM08-2A", mode: "Laser diffraction particle size analyzer - dry measurement (Instrument use)", unit: "hour", mahidol: 300, gov: 400, priv: 600 },
      { group: "Spectrometer", instrument: "Laser diffraction particle size analyzer", code: "SM08-1D", mode: "Laser diffraction particle size analyzer - wet measurement (Test)", unit: "sample", mahidol: 350, gov: 450, priv: 700 },
      { group: "Spectrometer", instrument: "Laser diffraction particle size analyzer", code: "SM08-2D", mode: "Laser diffraction particle size analyzer - dry measurement (Test)", unit: "sample", mahidol: 400, gov: 500, priv: 800 },
      { group: "Spectrometer", instrument: "NMR spectrometer", code: "SM09-1A", mode: "NMR 400 MHz (Instrument use)", unit: "hour", mahidol: 450, gov: 600, priv: 900 },
      { group: "Spectrometer", instrument: "NMR spectrometer", code: "SM09-2A", mode: "NMR 500 MHz (Instrument use)", unit: "hour", mahidol: 600, gov: 750, priv: 1200 },
      { group: "Spectrometer", instrument: "NMR spectrometer", code: "SM09-1B", mode: "NMR 400 MHz (Program analysis)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Spectrometer", instrument: "NMR spectrometer", code: "SM09-2B", mode: "NMR 500 MHz (Program analysis)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Spectrometer", instrument: "NMR spectrometer", code: "SM09-1C", mode: "NMR 400 MHz - 1D (Test and analysis)", unit: "sample", mahidol: 550, gov: 700, priv: 1100 },
      { group: "Spectrometer", instrument: "NMR spectrometer", code: "SM09-2C", mode: "NMR 400 MHz - 2D (Test and analysis)", unit: "sample", mahidol: 750, gov: 950, priv: 1500 },
      { group: "Spectrometer", instrument: "NMR spectrometer", code: "SM09-3C", mode: "NMR 400 MHz - special (Test and analysis)", unit: "sample", mahidol: 1500, gov: 1900, priv: 3000 },
      { group: "Spectrometer", instrument: "NMR spectrometer", code: "SM09-4C", mode: "NMR 500 MHz - 1D (Test and analysis)", unit: "sample", mahidol: 750, gov: 950, priv: 1500 },
      { group: "Spectrometer", instrument: "NMR spectrometer", code: "SM09-5C", mode: "NMR 500 MHz - 2D (Test and analysis)", unit: "sample", mahidol: 1000, gov: 1250, priv: 2000 },
      { group: "Spectrometer", instrument: "NMR spectrometer", code: "SM09-6C", mode: "NMR 500 MHz - special (Test and analysis)", unit: "sample", mahidol: 2000, gov: 2500, priv: 4000 },
      { group: "Spectrometer", instrument: "NMR spectrometer", code: "SM09-1D", mode: "NMR 400 MHz - 1D 1H (Test)", unit: "sample", mahidol: 400, gov: 500, priv: 800 },
      { group: "Spectrometer", instrument: "NMR spectrometer", code: "SM09-2D", mode: "NMR 400 MHz - 1D 13C, 19F, 31P (Test)", unit: "sample", mahidol: 500, gov: 650, priv: 1000 },
      { group: "Spectrometer", instrument: "NMR spectrometer", code: "SM09-3D", mode: "NMR 500 MHz - 1D 1H (Test)", unit: "sample", mahidol: 550, gov: 700, priv: 1100 },
      { group: "Spectrometer", instrument: "NMR spectrometer", code: "SM09-4D", mode: "NMR 500 MHz - 1D 13C, 19F, 31P (Test)", unit: "sample", mahidol: 650, gov: 850, priv: 1300 },
      { group: "Spectrometer", instrument: "Raman spectrometer", code: "SM10-1A", mode: "Raman spectrometer (Instrument use)", unit: "hour", mahidol: 450, gov: 600, priv: 900 },
      { group: "Spectrometer", instrument: "Raman spectrometer", code: "SM10-2A", mode: "Raman microscope (Instrument use)", unit: "hour", mahidol: 600, gov: 750, priv: 1200 },
      { group: "Spectrometer", instrument: "Raman spectrometer", code: "SM10-1B", mode: "Raman spectrometer (Program analysis)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Spectrometer", instrument: "Raman spectrometer", code: "SM10-2B", mode: "Raman microscope (Program analysis)", unit: "hour", mahidol: 250, gov: 350, priv: 500 },
      { group: "Spectrometer", instrument: "Raman spectrometer", code: "SM10-1D", mode: "Raman spectrometer (Test)", unit: "sample", mahidol: 550, gov: 700, priv: 1100 },
      { group: "Spectrometer", instrument: "Raman spectrometer", code: "SM10-2D", mode: "Raman microscope - point measurement (Test)", unit: "sample", mahidol: 800, gov: 1000, priv: 1600 },
      { group: "Spectrometer", instrument: "Raman spectrometer", code: "SM10-3D", mode: "Raman microscope - mapping (Test)", unit: "hour", mahidol: 1400, gov: 1750, priv: 2800 },
      { group: "Spectrometer", instrument: "UV-Vis spectrophotometer", code: "SM11-1A", mode: "UV-Vis (Instrument use)", unit: "hour", mahidol: 50, gov: 75, priv: 100 },
      { group: "Spectrometer", instrument: "UV-Vis spectrophotometer", code: "SM11-1B", mode: "UV-Vis (Program analysis)", unit: "hour", mahidol: 30, gov: 40, priv: 60 },
      { group: "Spectrometer", instrument: "UV-Vis spectrophotometer", code: "SM11-1D", mode: "UV-Vis (Test)", unit: "sample", mahidol: 80, gov: 100, priv: 160 },
      { group: "Spectrometer", instrument: "UV-Vis-NIR spectrophotometer", code: "SM12-1A", mode: "UV-Vis-NIR (Instrument use)", unit: "hour", mahidol: 250, gov: 350, priv: 500 },
      { group: "Spectrometer", instrument: "UV-Vis-NIR spectrophotometer", code: "SM12-1B", mode: "UV-Vis-NIR (Program analysis)", unit: "hour", mahidol: 100, gov: 150, priv: 200 },
      { group: "Spectrometer", instrument: "UV-Vis-NIR spectrophotometer", code: "SM12-1D", mode: "UV-Vis-NIR (Test)", unit: "sample", mahidol: 300, gov: 400, priv: 600 },

      // ────────────────── Surface analysis instrument ──────────────────
      { group: "Surface analysis instrument", instrument: "Contact angle meter", code: "SA01-1A", mode: "Contact angle meter (Instrument use)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Surface analysis instrument", instrument: "Contact angle meter", code: "SA01-1D", mode: "Contact angle meter (Test)", unit: "sample", mahidol: 200, gov: 250, priv: 400 },
      { group: "Surface analysis instrument", instrument: "Surface area and porosity analyzer", code: "SA02-1A", mode: "BET (Instrument use)", unit: "hour", mahidol: 350, gov: 450, priv: 700 },
      { group: "Surface analysis instrument", instrument: "Surface area and porosity analyzer", code: "SA02-2A", mode: "BET - degas (Instrument use)", unit: "hour", mahidol: 100, gov: 150, priv: 200 },
      { group: "Surface analysis instrument", instrument: "Surface area and porosity analyzer", code: "SA02-1B", mode: "BET (Program analysis)", unit: "hour", mahidol: 150, gov: 200, priv: 300 },
      { group: "Surface analysis instrument", instrument: "Surface area and porosity analyzer", code: "SA02-1C", mode: "BET - surface area (Test and analysis)", unit: "sample", mahidol: 700, gov: 900, priv: 1400 },
      { group: "Surface analysis instrument", instrument: "Surface area and porosity analyzer", code: "SA02-2C", mode: "BET - porosity (Test and analysis)", unit: "sample", mahidol: 1200, gov: 1500, priv: 2400 },
      { group: "Surface analysis instrument", instrument: "Surface area and porosity analyzer", code: "SA02-1D", mode: "BET - degas (Test)", unit: "sample", mahidol: 200, gov: 250, priv: 400 },

      // ────────────────── Thermal analysis instrument ──────────────────
      { group: "Thermal analysis instrument", instrument: "Simultaneous thermal analyzer : STA", code: "TM01-1A", mode: "Automated-STA (Instrument use)", unit: "hour", mahidol: 350, gov: 450, priv: 700 },
      { group: "Thermal analysis instrument", instrument: "Simultaneous thermal analyzer : STA", code: "TM01-2A", mode: "STA (Instrument use)", unit: "hour", mahidol: 350, gov: 450, priv: 700 },
      { group: "Thermal analysis instrument", instrument: "Simultaneous thermal analyzer : STA", code: "TM01-1B", mode: "Automated-STA (Program analysis)", unit: "hour", mahidol: 450, gov: 600, priv: 900 },
      { group: "Thermal analysis instrument", instrument: "Simultaneous thermal analyzer : STA", code: "TM01-2B", mode: "STA (Program analysis)", unit: "hour", mahidol: 150, gov: 200, priv: 300 },
      { group: "Thermal analysis instrument", instrument: "Simultaneous thermal analyzer : STA", code: "TM01-1C", mode: "Automated-STA (Test and analysis)", unit: "hour", mahidol: 150, gov: 200, priv: 300 },
      { group: "Thermal analysis instrument", instrument: "Simultaneous thermal analyzer : STA", code: "TM01-2C", mode: "STA (Test and analysis)", unit: "sample", mahidol: 400, gov: 500, priv: 800 },
      { group: "Thermal analysis instrument", instrument: "Differential scanning calorimeter : DSC", code: "TM02-1A", mode: "DSC - medium pressure sample (Instrument use)", unit: "sample", mahidol: 400, gov: 500, priv: 800 },
      { group: "Thermal analysis instrument", instrument: "Differential scanning calorimeter : DSC", code: "TM02-2A", mode: "DSC - medium pressure sample (Instrument use with user's crucible)", unit: "sample", mahidol: 600, gov: 750, priv: 1200 },
      { group: "Thermal analysis instrument", instrument: "Differential scanning calorimeter : DSC", code: "TM02-3A", mode: "DSC - standard sample (Instrument use)", unit: "hour", mahidol: 450, gov: 600, priv: 900 },
      { group: "Thermal analysis instrument", instrument: "Differential scanning calorimeter : DSC", code: "TM02-4A", mode: "DSC - standard sample (Instrument use with user crucible)", unit: "hour", mahidol: 600, gov: 750, priv: 1200 },
      { group: "Thermal analysis instrument", instrument: "Differential scanning calorimeter : DSC", code: "TM02-1B", mode: "DSC (Program analysis)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "Thermal analysis instrument", instrument: "Differential scanning calorimeter : DSC", code: "TM02-1C", mode: "DSC - high pressure sample (Test and analysis)", unit: "sample", mahidol: 600, gov: 750, priv: 1200 },
      { group: "Thermal analysis instrument", instrument: "Differential scanning calorimeter : DSC", code: "TM02-2C", mode: "DSC - high pressure sample (Test and analysis with user crucible)", unit: "sample", mahidol: 900, gov: 1150, priv: 1800 },
      { group: "Thermal analysis instrument", instrument: "Differential scanning calorimeter : DSC", code: "TM02-3C", mode: "DSC - standard sample (Test and analysis)", unit: "sample", mahidol: 500, gov: 650, priv: 1000 },
      { group: "Thermal analysis instrument", instrument: "Differential scanning calorimeter : DSC", code: "TM02-4C", mode: "DSC - standard sample (Test and analysis with user crucible)", unit: "sample", mahidol: 700, gov: 900, priv: 1400 },

      // ────────────────── Water purification system ──────────────────
      { group: "Water purification system", instrument: "Water purification system", code: "WP01-1A", mode: "Type l (LC-MS grade, resistivity 18.2 MΩ·cm)", unit: "Litre", mahidol: 150, gov: 200, priv: 300 },
      { group: "Water purification system", instrument: "Water purification system", code: "WP01-2A", mode: "Type l (Resistivity 18.2 MΩ·cm)", unit: "Litre", mahidol: 60, gov: 80, priv: 120 },
      { group: "Water purification system", instrument: "Water purification system", code: "WP01-3A", mode: "Type ll (Resistivity > 5 MΩ·cm)", unit: "Litre", mahidol: 30, gov: 40, priv: 60 },
      { group: "Water purification system", instrument: "Water purification system", code: "WP01-4A", mode: "Type III (RO water)", unit: "Litre", mahidol: 5, gov: 10, priv: 15 },

      // ────────────────── X-ray-based instrument ──────────────────
      { group: "X-ray-based instrument", instrument: "Nanoscale X-ray computed tomograph : Nano-CT", code: "XR01-1A", mode: "Nano-CT (Instrument use)", unit: "hour", mahidol: 700, gov: 900, priv: 1400 },
      { group: "X-ray-based instrument", instrument: "Nanoscale X-ray computed tomograph : Nano-CT", code: "XR01-1B", mode: "Nano-CT (Program analysis)", unit: "hour", mahidol: 600, gov: 750, priv: 1200 },
      { group: "X-ray-based instrument", instrument: "X-ray diffractometer : XRD", code: "XR02-1A", mode: "Benchtop-XRD - phase identification, phase analysis (Instrument use)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "X-ray-based instrument", instrument: "X-ray diffractometer : XRD", code: "XR02-2A", mode: "XRD - phase identification, phase analysis (Instrument use)", unit: "hour", mahidol: 600, gov: 750, priv: 1200 },
      { group: "X-ray-based instrument", instrument: "X-ray diffractometer : XRD", code: "XR02-3A", mode: "XRD - temperature control, X-ray reflectivity, grazing incidence diffraction, texture and pole figures (Instrument use)", unit: "hour", mahidol: 1200, gov: 1500, priv: 2400 },
      { group: "X-ray-based instrument", instrument: "X-ray diffractometer : XRD", code: "XR02-1B", mode: "Benchtop-XRD (Program analysis)", unit: "hour", mahidol: 100, gov: 150, priv: 200 },
      { group: "X-ray-based instrument", instrument: "X-ray diffractometer : XRD", code: "XR02-1C", mode: "Benchtop-XRD - phase identification, phase analysis (Test and analysis)", unit: "hour", mahidol: 450, gov: 600, priv: 900 },
      { group: "X-ray-based instrument", instrument: "X-ray diffractometer : XRD", code: "XR02-2C", mode: "XRD - phase identification, phase analysis (Test and analysis)", unit: "hour", mahidol: 1350, gov: 1750, priv: 2700 },
      { group: "X-ray-based instrument", instrument: "X-ray diffractometer : XRD", code: "XR02-1D", mode: "Benchtop-XRD - phase identification, phase analysis (Test)", unit: "hour", mahidol: 300, gov: 400, priv: 600 },
      { group: "X-ray-based instrument", instrument: "X-ray diffractometer : XRD", code: "XR02-2D", mode: "XRD - phase identification, phase analysis (Test)", unit: "hour", mahidol: 900, gov: 1150, priv: 1800 },
      { group: "X-ray-based instrument", instrument: "X-ray diffractometer : XRD", code: "XR02-3D", mode: "XRD - temperature control, X-ray reflectivity, grazing incidence diffraction, texture and pole figures (Test)", unit: "hour", mahidol: 1800, gov: 2250, priv: 3600 },
      { group: "X-ray-based instrument", instrument: "X-ray fluorescence : XRF", code: "XR04-1A", mode: "Micro-XRF - point measurement, mapping (Instrument use)", unit: "hour", mahidol: 450, gov: 600, priv: 900 },
      { group: "X-ray-based instrument", instrument: "X-ray fluorescence : XRF", code: "XR04-2A", mode: "WDXRF (Instrument use)", unit: "sample", mahidol: 300, gov: 400, priv: 600 },
      { group: "X-ray-based instrument", instrument: "X-ray fluorescence : XRF", code: "XR04-1B", mode: "Micro-XRF (Program analysis)", unit: "hour", mahidol: 250, gov: 300, priv: 500 },
      { group: "X-ray-based instrument", instrument: "X-ray fluorescence : XRF", code: "XR04-2B", mode: "WDXRF (Program analysis)", unit: "hour", mahidol: 200, gov: 250, priv: 400 },
      { group: "X-ray-based instrument", instrument: "X-ray fluorescence : XRF", code: "XR04-1D", mode: "Micro-XRF - point measurement, mapping (Test)", unit: "hour", mahidol: 700, gov: 900, priv: 1400 },
      { group: "X-ray-based instrument", instrument: "X-ray fluorescence : XRF", code: "XR04-2D", mode: "WDXRF (Test)", unit: "sample", mahidol: 600, gov: 750, priv: 1200 },

      // ────────────────── Special tests ──────────────────
      { group: "Special tests", instrument: "Special test 1", code: "ST01-D", mode: "Special test 1", unit: "sample", mahidol: 100, gov: 150, priv: 200 },
      { group: "Special tests", instrument: "Special test 2", code: "ST02-D", mode: "Special test 2", unit: "sample", mahidol: 200, gov: 250, priv: 400 },
      { group: "Special tests", instrument: "Special test 3", code: "ST03-D", mode: "Special test 3", unit: "sample", mahidol: 500, gov: 650, priv: 1000 },
      { group: "Special tests", instrument: "Special test 4", code: "ST04-D", mode: "Special test 4", unit: "sample", mahidol: 1000, gov: 1250, priv: 2000 },
      { group: "Special tests", instrument: "Special test 5", code: "ST05-D", mode: "Special test 5", unit: "sample", mahidol: 2000, gov: 2500, priv: 4000 },
      { group: "Special tests", instrument: "Special test 6", code: "ST06-D", mode: "Special test 6", unit: "sample", mahidol: 3000, gov: 4000, priv: 6000 },
      { group: "Special tests", instrument: "Special test 7", code: "ST07-D", mode: "Special test 7", unit: "sample", mahidol: 5000, gov: 7000, priv: 10000 },
      { group: "Special tests", instrument: "Special test 8", code: "ST08-D", mode: "Special test 8", unit: "sample", mahidol: 10000, gov: 12500, priv: 20000 },
    ];

    // ===== GROUP CONFIG =====
    const groupConfig = {
      "Bioscience instrument": { key: "bioscience", icon: "🧬", label: "Bioscience Instrument" },
      "Chromatograph": { key: "chromatograph", icon: "🧪", label: "Chromatograph" },
      "Freezer": { key: "freezer", icon: "❄️", label: "Freezer" },
      "Microscope": { key: "microscope", icon: "🔬", label: "Microscope" },
      "Sample preparation": { key: "sample-prep", icon: "⚗️", label: "Sample Preparation" },
      "Spectrometer": { key: "spectrometer", icon: "📊", label: "Spectrometer" },
      "Surface analysis instrument": { key: "surface", icon: "🔍", label: "Surface Analysis" },
      "Thermal analysis instrument": { key: "thermal", icon: "🌡️", label: "Thermal Analysis" },
      "Water purification system": { key: "water", icon: "💧", label: "Water Purification" },
      "X-ray-based instrument": { key: "xray", icon: "☢️", label: "X-ray Instrument" },
      "Special tests": { key: "special", icon: "⭐", label: "Special Tests" },
    };
